android_library(
  name = "arkan_android",
  srcs = ["java/com/kleinstein/arkan/Greeting.java"],
  resource_files = glob(["res/**/*"]),
  custom_package = "com.kleinstein.arkan",
  manifest = "Manifest.xml",
  deps = ["//lib/cpp:arkan"],
)
